export type Organization = {
  timestamp: string,
  support: boolean,
  org_name: string,
  url: string,
  states: string,
  authorized: boolean,
  name: string,
  email: string,
  phone: any,
  logo: string,
  alt_email: string,
  organize: boolean,
  use_logo: boolean,
  take_actions: string,
};

export const organizations: Organization[] = [
  {
    "timestamp": "4/10/2021 13:11:21",
    "support": true,
    "org_name": "Mona foundation",
    "url": "www.monaaudufoundation.com",
    "states": "FCT Abuja, Nigeria",
    "authorized": true,
    "name": "Chris Obi",
    "email": "Krisook2@gmail.com",
    "phone": "+234-8034102562",
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": false,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "4/11/2021 12:50:58",
    "support": true,
    "org_name": "Climate Crisis Policy",
    "url": "www.climatecrisispolicy.org",
    "states": "Many",
    "authorized": true,
    "name": "Todd Fernandez",
    "email": "climatecrisispolicy@gmail.com",
    "phone": 6463516498,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "4/11/2021 17:28:54",
    "support": true,
    "org_name": "North Country Earth Action",
    "url": "www.northcountryearthaction.org and www.facebook.com/northcountryearthaction",
    "states": "NY",
    "authorized": true,
    "name": "Lisa Adamson",
    "email": "ladamson27@gmail.com",
    "phone": "518 307 7842",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "4/16/2021 10:15:14",
    "support": true,
    "org_name": "Earth Ethics, Inc.",
    "url": "www.earthethicsaction.us",
    "states": "Gulf Coast States",
    "authorized": true,
    "name": "Mary Gutierrez",
    "email": "Earthethicsaction@gmail.com",
    "phone": 8505497472,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "4/16/2021 10:47:39",
    "support": true,
    "org_name": "Hazon",
    "url": "hazon.org",
    "states": "NY, MI",
    "authorized": true,
    "name": "Nigel Savage, Jakir Manela",
    "email": "jakir@hazon.org",
    "phone": 9177429979,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "4/18/2021 11:58:12",
    "support": true,
    "org_name": "New York Grassroots Alliance",
    "url": "",
    "states": "New York",
    "authorized": true,
    "name": "Dr. Susan Spieler",
    "email": "love.our.only.planet@gmail.com",
    "phone": "212.877-0355",
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": false,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "4/18/2021 15:14:45",
    "support": true,
    "org_name": "Thomas Berry Forum",
    "url": "https://www.iona.edu/academics/schools-institutes/kathleen-deignan-cnd-institute-earth-and-spirit/thomas-berry-forum",
    "states": "NY",
    "authorized": true,
    "name": "Kevin Cawley",
    "email": "kcawley1@mac.com",
    "phone": 19142604512,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "4/18/2021 17:07:43",
    "support": true,
    "org_name": "Fox Valley Citizens for Peace & Justice",
    "url": "www.fvc4pnj.org",
    "states": "IL",
    "authorized": true,
    "name": "Mary Shesgreen",
    "email": "marysedrop@att.net",
    "phone": 8477421406,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "4/18/2021 21:45:04",
    "support": true,
    "org_name": "350 Chicago",
    "url": "",
    "states": "Illinois",
    "authorized": true,
    "name": "Melissa Brice",
    "email": "Info@350chicago.org",
    "phone": 8472935743,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "4/19/2021 8:27:07",
    "support": true,
    "org_name": "Climate Psychology Alliance North America",
    "url": "www.climatepsychology.us",
    "states": "NY, CT, ME, PA, DC, NJ, WA, CA, OR",
    "authorized": true,
    "name": "Merritt Juliano",
    "email": "Mjuliano@climatepsychology.us",
    "phone": "917-224-9598",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "4/23/2021 12:47:10",
    "support": true,
    "org_name": "People for a Healthy Environment",
    "url": "https://www.facebook.com/pheinc1/",
    "states": "NY",
    "authorized": true,
    "name": "Doug Couchon",
    "email": "dcouchon@yahoo.com",
    "phone": 16074257203,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "",

  },
  {
    "timestamp": "4/23/2021 14:20:17",
    "support": true,
    "org_name": "GreenLatinos",
    "url": "greenlatinos.org",
    "states": "Federal",
    "authorized": true,
    "name": "Andrea Marpillero-Colomina",
    "email": "andreacolomina@greenlatinos.org",
    "phone": "Email please!",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Join the Earth Bill Network",

  },
  {
    "timestamp": "4/24/2021 18:37:13",
    "support": true,
    "org_name": "Save Our Illinois Land",
    "url": "http://saveourillinoisland.org/",
    "states": "Illinois",
    "authorized": true,
    "name": "Deni Mathews",
    "email": "dmathews@saveourillinoisland.org",
    "phone": "(847) 893-9095",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "4/24/2021 23:54:08",
    "support": true,
    "org_name": "Beloved Earth Community of The Riverside Church",
    "url": "trcnyc.org/ministries/belovedearth/",
    "states": "NY",
    "authorized": true,
    "name": "Rev. Dr. Alan Bentz-Letts",
    "email": "alanbentzletts@gmail.com",
    "phone": 16462169809,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "4/25/2021 14:22:28",
    "support": true,
    "org_name": "350 Kishwaukee",
    "url": "https://350kishwaukee.org/",
    "states": "Illinois",
    "authorized": true,
    "name": "Meryl Greer Domina",
    "email": "merylkgd@gmail.com",
    "phone": "815  758-4827",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "4/27/2021 2:06:40",
    "support": true,
    "org_name": "Aytzim: Ecological Judaism",
    "url": "https://aytzim.org",
    "states": "Nationwide",
    "authorized": true,
    "name": "David Krantz",
    "email": "info@aytzim.org",
    "phone": 3475594492,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "4/27/2021 14:55:46",
    "support": true,
    "org_name": "Santa Cruz Climate Action Network",
    "url": "scruzclimate.org",
    "states": "CA",
    "authorized": true,
    "name": "pauline seales",
    "email": "paulineseales120@gmail.com",
    "phone": 18314282080,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "4/27/2021 20:06:46",
    "support": true,
    "org_name": "Community for Earth First Unitarian Church Portland, OR",
    "url": "apickar@cs.com",
    "states": "Oregon",
    "authorized": true,
    "name": "Ann Pickar",
    "email": "apickar@cs.com",
    "phone": 15032468629,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts",

  },
  {
    "timestamp": "4/30/2021 13:38:45",
    "support": true,
    "org_name": "Unitarian Universalists for a Just Economic Community",
    "url": "uujec.org",
    "states": "Nationwide",
    "authorized": true,
    "name": "Terry L Lowman",
    "email": "terryleelowman@gmail.com",
    "phone": 15154419844,
    "logo": "https://drive.google.com/open?id=1K5epthL1u0maWBb66HxEMJnj1egvlJ9i",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join shared Marketing Efforts",

  },
  {
    "timestamp": "4/30/2021 18:38:37",
    "support": true,
    "org_name": "Interfaith Public Health Network",
    "url": "https://www.iphnetwork.org/",
    "states": "NY but expanding nationally",
    "authorized": true,
    "name": "Kelly Moltzen",
    "email": "kelly@iphnetwork.org",
    "phone": 8453041521,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts",

  },
  {
    "timestamp": "5/1/2021 11:35:00",
    "support": true,
    "org_name": "Clean Energy Action - Colorado",
    "url": "https://www.cleanenergyaction.org/",
    "states": "Regional",
    "authorized": true,
    "name": "Alison Burchell",
    "email": "burchell.alison@gmail.com",
    "phone": 13034992711,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network, Coordinate on Congressional Outreach, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "5/1/2021 11:48:50",
    "support": true,
    "org_name": "Empower our Future",
    "url": "EmpowerOurFuture.org",
    "states": "CO",
    "authorized": true,
    "name": "Alison Burchell",
    "email": "burchell.alison@gmail.com",
    "phone": 13034992711,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network, Coordinate on Congressional Outreach, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "5/1/2021 12:28:05",
    "support": true,
    "org_name": "REACT",
    "url": "REACT DeKalb (Facebook)",
    "states": "Illinois",
    "authorized": true,
    "name": "CYNTHIA DE SEIFE",
    "email": "civicsreboot@gmail.com",
    "phone": "815-621-8859",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Email our Lists, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "5/4/2021 11:28:59",
    "support": true,
    "org_name": "Circle Pines Center",
    "url": "http://circlepinescenter.org",
    "states": "Michigan, Illinois",
    "authorized": true,
    "name": "Sasha Ospina",
    "email": "sasha@circlepinescenter.org",
    "phone": 2699933428,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "5/5/2021 11:35:27",
    "support": true,
    "org_name": "Metro NY Catholic Climate Movement",
    "url": "",
    "states": "New York",
    "authorized": true,
    "name": "Nancy Lorence",
    "email": "n.lorence2013@gmail.com",
    "phone": 17188538741,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": false,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "5/5/2021 16:35:29",
    "support": true,
    "org_name": "St Francis Xavier Church",
    "url": "Instagram santistc",
    "states": "NY",
    "authorized": true,
    "name": "Christine Santisteban",
    "email": "Santistc@tcd.ie",
    "phone": 9293225748,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "5/13/2021 13:16:32",
    "support": true,
    "org_name": "Fridays for Future NYC",
    "url": "fridaysforfuturenyc.com",
    "states": "New York (and a little bit nationally)",
    "authorized": true,
    "name": "Anna Kathawala",
    "email": "f4f.nyc@gmail.com",
    "phone": 6469549529,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "5/15/2021 18:12:04",
    "support": true,
    "org_name": "National Capital Commission",
    "url": "",
    "states": "Ontario",
    "authorized": true,
    "name": "Arto Keklikian",
    "email": "arto.keklikian@ncc-ccn.ca",
    "phone": 6135135406,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts",

  },
  {
    "timestamp": "5/25/2021 16:33:24",
    "support": true,
    "org_name": "San Luis Valley Local Foods Coalition",
    "url": "www.slvlocalfoods.org",
    "states": "Colorado",
    "authorized": true,
    "name": "Max Gibson",
    "email": "directorslvlocalfoods@gmail.com, Max.slvlocalfoods@gmail.comMax.slvlocalfoods@gmail.com",
    "phone": "719-539-5606",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "5/25/2021 21:07:37",
    "support": true,
    "org_name": "Fridays for Future USA",
    "url": "fridaysforfutureusa.org",
    "states": "National",
    "authorized": true,
    "name": "Katharina Maier",
    "email": "partner@fridaysforfutureusa.org",
    "phone": 8143082374,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "5/28/2021 13:40:18",
    "support": true,
    "org_name": "350 Brooklyn",
    "url": "https://350brooklyn.org/",
    "states": "New York State",
    "authorized": true,
    "name": "Sara Gronim",
    "email": "legislation@350Brooklyn.org",
    "phone": "718-344-5835",
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Coordinate on Congressional Outreach, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "5/31/2021 22:55:30",
    "support": true,
    "org_name": "Think Zero LLC",
    "url": "www.thinkzerollc.com",
    "states": "Colorado, New York, Maine",
    "authorized": true,
    "name": "Sarah Currie-Halpern",
    "email": "sach@thinkzero.com",
    "phone": 9174985748,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "6/3/2021 20:06:05",
    "support": true,
    "org_name": "Interfaith Moral Action on Climate",
    "url": "https://www.interfaithmoralactiononclimate.org",
    "states": "USA",
    "authorized": true,
    "name": "David Krantz",
    "email": "info@aytzim.org",
    "phone": 3475594492,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "6/4/2021 16:38:55",
    "support": true,
    "org_name": "Executive Training Systems",
    "url": "www.lifeinsmallbites.com",
    "states": "United States",
    "authorized": true,
    "name": "James G Yarbrough",
    "email": "jimyarb@gmail.com",
    "phone": 5592323297,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Join the Earth Bill Network, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "6/7/2021 1:19:08",
    "support": true,
    "org_name": "Olympic Climate Action",
    "url": "www.olyclimate.org",
    "states": "United States",
    "authorized": true,
    "name": "Ed Chadd",
    "email": "olyclimate@olyclimate.org",
    "phone": 3607759234,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "6/10/2021 15:31:57",
    "support": true,
    "org_name": "Green Team Academy",
    "url": "www.greenteamacademy.com",
    "states": "Nationwide USA and globally",
    "authorized": true,
    "name": "Gin DeMaio",
    "email": "greenteam@ytbglobal.org",
    "phone": 7202247020,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network",

  },
  {
    "timestamp": "6/23/2021 12:11:31",
    "support": true,
    "org_name": "Coalition to Protect New York",
    "url": "www.facebook.com/CPNewYork",
    "states": "New York, NE USA, National USA",
    "authorized": true,
    "name": "Maura Stephens",
    "email": "maurastephens1@gmail.com",
    "phone": 6073513766,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "6/24/2021 16:26:30",
    "support": true,
    "org_name": "Charleston Climate Coalition",
    "url": "www.charlestonclimatecoalition.com",
    "states": "South Carolina",
    "authorized": true,
    "name": "Jen Wright & Belvin Olasov",
    "email": "charlestonclimatecoalition@gmail.com",
    "phone": 8435662178,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network",

  },
  {
    "timestamp": "6/25/2021 14:41:58",
    "support": true,
    "org_name": "Our Revolution Lake County",
    "url": "http://lakecountyrevolution.com/ On Facebook and twitter @orlakeco",
    "states": "Illinois",
    "authorized": true,
    "name": "Adam Broad",
    "email": "broadcoalition@gmail.com",
    "phone": 2247033423,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "8/17/2021 21:52:45",
    "support": true,
    "org_name": "Hempbest",
    "url": "Www.Hemp-Best.Com",
    "states": "United States",
    "authorized": true,
    "name": "Tobias Feuling",
    "email": "rocky@hempbestcbdoil.com",
    "phone": 5417198733,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "10/9/2021 15:11:59",
    "support": true,
    "org_name": "Church Women United in New York State",
    "url": "https://www.churchwomenunited.net/",
    "states": "New York State",
    "authorized": true,
    "name": "Mary Smith",
    "email": "smithmarym@yahoo.com",
    "phone": 1111111111,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "",

  },
  {
    "timestamp": "10/9/2021 16:35:45",
    "support": true,
    "org_name": "White Rabbit Grove RDNA",
    "url": "https://www.facebook.com/whiterabbitgove",
    "states": "WI USA",
    "authorized": true,
    "name": "Helgaleena H",
    "email": "helgaleenas@yahoo.com",
    "phone": 6082550504,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "10/10/2021 14:35:23",
    "support": true,
    "org_name": "North American Climate, Conservation and Environment (NACCE)",
    "url": "www.globalwarmingisreal.com and www.cec.org",
    "states": "New York, USA",
    "authorized": true,
    "name": "Jerry Rivers",
    "email": "jerry.rivers13@yahoo.com",
    "phone": 5166704461,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts",

  },
  {
    "timestamp": "1/1/2022 13:55:42",
    "support": true,
    "org_name": "Terra Advocati",
    "url": "terraadvocati.org",
    "states": "Texas, New Mexico",
    "authorized": true,
    "name": "Timothy Edward Duda",
    "email": "timduda@aol.com",
    "phone": "+2108224525",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "1/2/2022 10:57:03",
    "support": true,
    "org_name": "Manhattan Solid Waste Advisory Board",
    "url": "https://www.manhattanswab.org/",
    "states": "New York",
    "authorized": true,
    "name": "Manhattan Solid Waste Advisory Board",
    "email": "manhattanswab1@gmail.com",
    "phone": "917-456-7111",
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": false,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "1/3/2022 17:47:04",
    "support": true,
    "org_name": "Elders Climate Action (ECA) Northern California (NorCal) Chapter",
    "url": "https://www.eldersclimateaction.org/norcal-chapter/",
    "states": "USA",
    "authorized": true,
    "name": "Todd Weber",
    "email": "toddnlil2020@gmail.com",
    "phone": 4082048341,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "1/4/2022 13:58:23",
    "support": true,
    "org_name": "Oceanic Global",
    "url": "https://oceanic.global/",
    "states": "U.S. & Global",
    "authorized": true,
    "name": "Cassia Patel",
    "email": "cassia@oceanic.global",
    "phone": "+1 (201) 710-0060",
    "logo": "",
    "alt_email": "Leah Tanner",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Join shared Marketing Efforts",
  },
  {
    "timestamp": "1/5/2022 20:19:02",
    "support": true,
    "org_name": "Sustainable Mill Valley",
    "url": "https://www.sustainablemillvalley.com/",
    "states": "Mill Valley City in Marin County, CA",
    "authorized": true,
    "name": "Marilyn Price",
    "email": "mprice@the-acorn.com",
    "phone": 14153812941,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "1/12/2022 16:28:07",
    "support": true,
    "org_name": "Chesapeake Climate Action Network",
    "url": "https://chesapeakeclimate.org/",
    "states": "United States",
    "authorized": true,
    "name": "Jamie DeMarco",
    "email": "jamie@chesapeakeclimate.org",
    "phone": 14438455601,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "",

  },
  {
    "timestamp": "1/18/2022 10:00:28",
    "support": true,
    "org_name": "Unitarian Universalist Ministry for Earth",
    "url": "https://www.uumfe.org/",
    "states": "US, Canada",
    "authorized": true,
    "name": "Rev. Dr. Leonisa Ardizzone",
    "email": "lardizzone@uuma.org, office@uumfe.org",
    "phone": 4698799744,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts",
  },
  {
    "timestamp": "1/18/2022 13:16:18",
    "support": true,
    "org_name": "Environment Matters",
    "url": "www.envmatters.org",
    "states": "Illinois",
    "authorized": true,
    "name": "Paul Berland",
    "email": "pnb3210@gmail.com",
    "phone": "773-739-6147",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "2/6/2022 0:12:09",
    "support": true,
    "org_name": "St. Francis De Sales Laudato Si Team",
    "url": "",
    "states": "New York district 12",
    "authorized": true,
    "name": "Kristin McDonough",
    "email": "kristinkrausemcdonough@gmail.com",
    "phone": "917 304 6684",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Coordinate on Congressional Outreach, Join shared Marketing Efforts",

  },
  {
    "timestamp": "2/16/2022 18:31:30",
    "support": true,
    "org_name": "Creation Care Team, Catholic Diocese of San Diego",
    "url": "sdcatholic.org/creation",
    "states": "California, United States",
    "authorized": true,
    "name": "Fr. Emmet Farrell",
    "email": "emmet.farrell619@gmail.com",
    "phone": "619-419-8345",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "2/16/2022 19:56:00",
    "support": true,
    "org_name": "First of Parish Concord MA Environmental Team",
    "url": "",
    "states": "Massachusetts",
    "authorized": true,
    "name": "Gail Kharidia",
    "email": "gail.kharidia@gmail.com",
    "phone": 9782018590,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "2/23/2022 10:43:49",
    "support": true,
    "org_name": "NYPAN Greene",
    "url": "https://www.facebook.com/nypangreene",
    "states": "NY",
    "authorized": true,
    "name": "Cari Gardner",
    "email": "cariyogi@gmail.com",
    "phone": 15184444593,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": false,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "2/23/2022 10:44:54",
    "support": true,
    "org_name": "NYPAN Enviro Committee",
    "url": "",
    "states": "NY",
    "authorized": true,
    "name": "Cari Gardner",
    "email": "cariyogi@gmail.com",
    "phone": 15184444593,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": false,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "2/23/2022 11:12:50",
    "support": true,
    "org_name": "WESPAC Foundation, Inc.",
    "url": "wespac.org",
    "states": "New York",
    "authorized": true,
    "name": "Nada Khader",
    "email": "wespacfoundation@gmail.com",
    "phone": 9144496514,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "3/24/2022 16:43:06",
    "support": true,
    "org_name": "Concerned Citizen of Calhoun County",
    "url": "Facebook",
    "states": "South Carolina",
    "authorized": true,
    "name": "E. Jeffrey Glover",
    "email": "gloverej@email.com",
    "phone": 8035154555,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Join the Earth Bill Network",

  },
  {
    "timestamp": "3/30/2022 23:33:43",
    "support": true,
    "org_name": "Advanced Organics",
    "url": "Www.advancedorganicsct.com",
    "states": "Ct USA",
    "authorized": true,
    "name": "Joe Quaranta",
    "email": "Office@Advancedorganicsct.com",
    "phone": 8602340516,
    "logo": "",
    "alt_email": "advancedindustriesus@gmail.com",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "3/30/2022 23:54:56",
    "support": true,
    "org_name": "Mission Its Possible",
    "url": "www.HelpingHandsforheros.com",
    "states": "United States Connecticut",
    "authorized": true,
    "name": "Joe Quaranta",
    "email": "Helpinghandsforheros2020@gmail.com",
    "phone": 18602340516,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "4/6/2022 9:06:02",
    "support": true,
    "org_name": "Occupy Bergen County",
    "url": "Twitter: @OccupyBergenC",
    "states": "New Jersey",
    "authorized": true,
    "name": "Sally Jane Gellert",
    "email": "SJGUU@aol.com",
    "phone": 2013672320,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "4/6/2022 11:42:55",
    "support": true,
    "org_name": "Gulf Coast Creation Care",
    "url": "www.gulfcoastcreationcare.org",
    "states": "Alabama, Mississipi, Florida",
    "authorized": true,
    "name": "Rhoda Vanderhart",
    "email": "rhodavanderhart@gmail.com",
    "phone": "913-406-3546",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "4/6/2022 19:42:27",
    "support": true,
    "org_name": "Poweshiek CARES",
    "url": "https://www.facebook.com/poweshiekcares/",
    "states": "Iowa",
    "authorized": true,
    "name": "Valerie Vetter",
    "email": "valvetter3@gmail.com",
    "phone": "641-821-9655",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "",

  },
  {
    "timestamp": "4/7/2022 16:17:45",
    "support": true,
    "org_name": "Jefferson County Farmers & Neighbors, Inc.",
    "url": "www.jfaniowa.org;   www.facebook.com/JFANIowa",
    "states": "Iowa",
    "authorized": true,
    "name": "Diane Rosenberg",
    "email": "jfan@lisco.com",
    "phone": "641-919-5002",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts",

  },
  {
    "timestamp": "4/12/2022 13:30:38",
    "support": true,
    "org_name": "Working Families Joliet",
    "url": "http://www.workingfamiliesjoliet.com/",
    "states": "Illinois",
    "authorized": true,
    "name": "Rachel Ventura",
    "email": "rachelfventura@gmail.com",
    "phone": "815-954-1981",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "4/18/2022 15:46:02",
    "support": true,
    "org_name": "Ecumenical Ministries of Oregon/Oregon Interfaith Power and Light",
    "url": "www.emoregon.org",
    "states": "Oregon",
    "authorized": true,
    "name": "Peter A. Sergienko",
    "email": "petersergienko@gmail.com",
    "phone": 15038418580,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network, Coordinate on Congressional Outreach, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "4/19/2022 15:39:30",
    "support": true,
    "org_name": "New York Progressive Action Network",
    "url": "https://nypan.org/",
    "states": "New York",
    "authorized": true,
    "name": "Cari Gardner",
    "email": "cariyogi@gmail.com",
    "phone": 15184444593,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "4/20/2022 14:45:05",
    "support": true,
    "org_name": "350 Washington County Portland",
    "url": "https://www.facebook.com/350PDXWashingtonCountyTeam",
    "states": "Washington County Portland Oregon",
    "authorized": true,
    "name": "Debby Garman",
    "email": "350washco@gmail.com",
    "phone": 15033185227,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "4/21/2022 13:16:40",
    "support": true,
    "org_name": "Cooper Climate Coalition (Cooper Union)",
    "url": "Climate.cooper.edu",
    "states": "New York Cuty",
    "authorized": true,
    "name": "Simon garb",
    "email": "Climate@cooper.edu",
    "phone": 9205747602,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "",

  },
  {
    "timestamp": "4/26/2022 17:21:26",
    "support": true,
    "org_name": "EcoFaith Recovery",
    "url": "https://www.ecofaithrecovery.org/",
    "states": "Oregon",
    "authorized": true,
    "name": "Peter Sergienko",
    "email": "petersergienko@gmail.com",
    "phone": "503-841-8580",
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "4/28/2022 22:33:37",
    "support": true,
    "org_name": "Colorado Jewish Climate Action",
    "url": "https://ColoradoJewishClimateAction.com/",
    "states": "Colorado",
    "authorized": true,
    "name": "Jason Moses",
    "email": "ColoradoJewishClimateAction@gmail.com",
    "phone": "510 290-1921",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts",

  },
  {
    "timestamp": "5/4/2022 14:35:12",
    "support": true,
    "org_name": "Open Table United Church of Christ",
    "url": "https://opentableucc.org",
    "states": "Alabama",
    "authorized": true,
    "name": "Rhoda Vanderhart",
    "email": "office@opentableucc.org",
    "phone": "913-406-3546",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "5/5/2022 0:48:12",
    "support": true,
    "org_name": "People for a Healthy Environment",
    "url": "https://www.facebook.com/pheinc1/",
    "states": "United States",
    "authorized": true,
    "name": "Doug Couchon",
    "email": "dcouchon@yahoo.com",
    "phone": 16074257203,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "5/5/2022 0:51:04",
    "support": true,
    "org_name": "Elmirans and Friends Against Fracking",
    "url": "https://www.facebook.com/ElmiransAgainstFracking/",
    "states": "New York",
    "authorized": true,
    "name": "Doug",
    "email": "dcouchon@yahoo.com",
    "phone": 16074257203,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "5/5/2022 0:57:15",
    "support": true,
    "org_name": "The Park Church, UCC",
    "url": "https://www.facebook.com/theparkchurch.org/",
    "states": "New York State",
    "authorized": true,
    "name": "Doug Couchon",
    "email": "dcouchon@yahoo.com",
    "phone": 16074257203,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "5/16/2022 8:32:06",
    "support": true,
    "org_name": "Elgin Green Groups 350org",
    "url": "www.ElginGreenGroups350.org",
    "states": "Illinois",
    "authorized": true,
    "name": "Sandra Kaptain",
    "email": "sakaptain@gmail.com",
    "phone": 8477417375,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "5/25/2022 14:47:52",
    "support": true,
    "org_name": "EARTHDAY.ORG",
    "url": "earthday.org (@EarthDay twitter @EarthDayNetwork instagram)",
    "states": "global",
    "authorized": true,
    "name": "Evan Raskin",
    "email": "raskin@earthday.org",
    "phone": 7816865513,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts",

  },
  {
    "timestamp": "7/28/2022 18:50:00",
    "support": true,
    "org_name": "Church of the Village",
    "url": "www.churchofthevillage.org",
    "states": "New York",
    "authorized": true,
    "name": "Jeff Wells",
    "email": "pastorjeff@churchofthevillage.org",
    "phone": "(917) 604-5227",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "9/19/2022 10:11:19",
    "support": true,
    "org_name": "Indigenous Earth Protectors",
    "url": "IEPforlife333",
    "states": "Minnesota",
    "authorized": true,
    "name": "Alex Golden-Wolf",
    "email": "Alexgoldenwolf67@gmail.com",
    "phone": "218-349-5640",
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "9/30/2022 22:08:49",
    "support": true,
    "org_name": "FrackBustersNY",
    "url": "http://www.frackbustersny.org/",
    "states": "New York State",
    "authorized": true,
    "name": "Mary Finneran",
    "email": "msfinn123@yahoo.com",
    "phone": "518-965-2935",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "12/15/2022 14:39:19",
    "support": true,
    "org_name": "Metuchen-Edison-Piscataway Area Branch NAACP",
    "url": "www.naacpmeab.org",
    "states": "United States",
    "authorized": true,
    "name": "Keith F Voos",
    "email": "keithvoos48@gmail.com",
    "phone": 7328419023,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Join the Earth Bill Network",

  },
  {
    "timestamp": "12/15/2022 14:43:11",
    "support": true,
    "org_name": "Drawdown NYC",
    "url": "drawdown-nyc.org",
    "states": "United States",
    "authorized": true,
    "name": "Keith F Voos",
    "email": "keithvoos48@gmail.com",
    "phone": 7329519154,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Join the Earth Bill Network",

  },
  {
    "timestamp": "12/19/2022 8:04:55",
    "support": true,
    "org_name": "SmogFree Denver",
    "url": "SmogFreeDenver.com",
    "states": "Colorado",
    "authorized": true,
    "name": "Theron D Makley",
    "email": "Tmakley@gmail.com",
    "phone": 3036011809,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "12/22/2022 7:25:36",
    "support": true,
    "org_name": "Colorado Coalition for a Livable Climate",
    "url": "https://colivableclimate.org/; https://www.facebook.com/COLivableClimate",
    "states": "Colorado",
    "authorized": true,
    "name": "Kevin Cross",
    "email": "JKEVIN87@COMCAST.NET",
    "phone": 19704843141,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "12/22/2022 15:10:17",
    "support": true,
    "org_name": "San Luis Valley Ecosystem Council",
    "url": "www.slvec.org",
    "states": "Colorado",
    "authorized": true,
    "name": "Christine Canaly",
    "email": "info@slvec.org",
    "phone": "719589-1518",
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "1/20/2023 10:43:10",
    "support": true,
    "org_name": "Earth Celebrations Inc",
    "url": "https://www.earthcelebrations.com",
    "states": "New York City, New York",
    "authorized": true,
    "name": "Felicia Young",
    "email": "felicia@earthcelebrations.com",
    "phone": 3477520854,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "1/26/2023 11:47:26",
    "support": true,
    "org_name": "Regenerative Intelligence",
    "url": "https://regenintel.earth",
    "states": "United States",
    "authorized": true,
    "name": "Mamta Mehra",
    "email": "mamta@regenintel.earth",
    "phone": "301-412-0208",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts",

  },
  {
    "timestamp": "2/8/2023 14:07:31",
    "support": true,
    "org_name": "Dominican Sisters In Committed Collaboration",
    "url": "www.opjustice.org",
    "states": "NY and NJ",
    "authorized": true,
    "name": "Didi Madden, OP",
    "email": "opsccjp@gmail.com",
    "phone": "347-538-7767",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network",

  },
  {
    "timestamp": "2/23/2023 11:40:43",
    "support": true,
    "org_name": "Independent Voters of Illinois IVI",
    "url": "https://www.iviipo.org/",
    "states": "Illinois",
    "authorized": true,
    "name": "Charles Paidock",
    "email": "cpaidock@hotmail.com",
    "phone": 13128425036,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "3/8/2023 21:38:36",
    "support": true,
    "org_name": "Nuclear Energy Information Service (NEIS)",
    "url": "www.neis.org",
    "states": "United States",
    "authorized": true,
    "name": "Dave Kraft",
    "email": "neis@neis.org",
    "phone": 7733427650,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "3/22/2023 14:18:31",
    "support": true,
    "org_name": "WakeUpWorld.earth",
    "url": "www.wakeupworld.earth",
    "states": "Washington state",
    "authorized": true,
    "name": "Anita Dygert-Gearheart",
    "email": "Adygertgearheart@hotmail.com",
    "phone": "541 951 2897",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "3/24/2023 14:00:27",
    "support": true,
    "org_name": "350 Montana",
    "url": "https://www.350montana.org/",
    "states": "Montana",
    "authorized": true,
    "name": "Marta Meengs",
    "email": "mmeengs77@gmail.com",
    "phone": "406-207-5252",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "4/5/2023 12:12:37",
    "support": true,
    "org_name": "The Heavy Lift Group",
    "url": "www.theheavyliftgroup.com",
    "states": "the Netherlands",
    "authorized": true,
    "name": "Murilo Caldana",
    "email": "Murilo@foxbrasil.com",
    "phone": "+5511998191146",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "4/12/2023 10:24:07",
    "support": true,
    "org_name": "Ohalah:the Association of Rabbis and Cantors for Jewish Renewal",
    "url": "www.neoblackhealthcoalition.org",
    "states": "Ohio",
    "authorized": true,
    "name": "YVONKA MARIE HALL",
    "email": "neobhc@gmail.com",
    "phone": 2168028101,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "4/12/2023 11:27:03",
    "support": true,
    "org_name": "AFGE Local 704",
    "url": "@704afge (Twitter)",
    "states": "IL, IN, MI, WI, MN, OH",
    "authorized": true,
    "name": "Nicole Cantello",
    "email": "704afge@gmail.com",
    "phone": 7732068131,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "4/14/2023 8:51:28",
    "support": true,
    "org_name": "350 Conejo / San Fernando Valley",
    "url": "",
    "states": "California",
    "authorized": true,
    "name": "Alan Weiner",
    "email": "Mighty30North@gmail.com",
    "phone": "818 309-5368",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "4/16/2023 9:40:36",
    "support": true,
    "org_name": "Dominican Leadership Conference",
    "url": "",
    "states": "multiple states",
    "authorized": true,
    "name": "Durstyne Farnan",
    "email": "ngo@domlife.org",
    "phone": "517.902.3408",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network",

  },
  {
    "timestamp": "4/18/2023 17:07:05",
    "support": true,
    "org_name": "Stand.earth",
    "url": "",
    "states": "US and Canada",
    "authorized": true,
    "name": "Nathan Taft",
    "email": "nathan@stand.earth",
    "phone": "+1 415-863-4563 ext 405",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join shared Marketing Efforts",

  },
  {
    "timestamp": "5/1/2023 17:02:45",
    "support": true,
    "org_name": "Unitarian Universalists for Social Justice",
    "url": "www.uusj.org; @twitter",
    "states": "United States",
    "authorized": true,
    "name": "Pablo DeJesus",
    "email": "pdejesus@uusj.org",
    "phone": 2024176428,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join shared Marketing Efforts",

  },
  {
    "timestamp": "5/10/2023 10:53:04",
    "support": true,
    "org_name": "Hispanic Access Foundation",
    "url": "hispanicaccess.org",
    "states": "National",
    "authorized": true,
    "name": "Shanna Edberg",
    "email": "shanna@hispanicaccess.org",
    "phone": 8186402936,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Join shared Marketing Efforts",

  },
  {
    "timestamp": "5/11/2023 15:24:43",
    "support": true,
    "org_name": "Rise and Resist",
    "url": "Riseandresist.org",
    "states": "New York",
    "authorized": true,
    "name": "Livvie Mann",
    "email": "Elizabethmann.livvie@gmail.com",
    "phone": 6468316422,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "",

  },
  {
    "timestamp": "5/12/2023 13:17:05",
    "support": true,
    "org_name": "Madhvi4EcoEthics",
    "url": "www.madhvi4ee.com",
    "states": "USA",
    "authorized": true,
    "name": "Madhvi Chittoor",
    "email": "madhvi4ecoethics@gmail.com",
    "phone": 7209036005,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "5/12/2023 14:18:56",
    "support": true,
    "org_name": "Chicago Greens",
    "url": "http://www.illinoisgreens.org/",
    "states": "Illinois",
    "authorized": true,
    "name": "Charles Paidock",
    "email": "cpaidock@hotmail.com",
    "phone": 3128425036,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "5/24/2023 13:43:51",
    "support": true,
    "org_name": "TRUST Climate Action Strategists",
    "url": "https://www.trustclimateactionstrategists.com/our-team",
    "states": "Colorado, Alaska, Hawaii, Wisconsin, USA",
    "authorized": true,
    "name": "Kat Haber@aol.com",
    "email": "KatHaber@aol.com",
    "phone": "907-299-2363",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network",

  },
  {
    "timestamp": "5/25/2023 11:47:21",
    "support": true,
    "org_name": "Daily Coffee News, Inc.",
    "url": "www.dailycoffeenews.com",
    "states": "U.S.",
    "authorized": true,
    "name": "Nick Brown",
    "email": "labrownie1@gmail.com",
    "phone": 6197886833,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "",

  },
  {
    "timestamp": "6/9/2023 15:43:55",
    "support": true,
    "org_name": "First United Methodist Church, Seattle",
    "url": "https://firstchurchseattle.org/",
    "states": "Washington State",
    "authorized": true,
    "name": "Tom Carlson",
    "email": "tomcarlson111151@gmail.com",
    "phone": "206-713-0832",
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "6/13/2023 22:14:02",
    "support": true,
    "org_name": "Vote Climate U.S. PAC",
    "url": "https://voteclimatepac.org/",
    "states": "U.S. House, U.S. Senate, Governors and select State Houses",
    "authorized": true,
    "name": "Karyn Strickler",
    "email": "karyn@voteclimatepac.org",
    "phone": 2404988726,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "7/19/2023 13:06:46",
    "support": true,
    "org_name": "Movement Rights",
    "url": "www.movementrights.org",
    "states": "United States",
    "authorized": true,
    "name": "Isabella Zizi",
    "email": "isabella@movementrights.org",
    "phone": 5109320978,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "",

  },
  {
    "timestamp": "7/19/2023 14:35:32",
    "support": true,
    "org_name": "Provinice of St. Mary Of the Capuchin Order",
    "url": "Capuchin.org",
    "states": "Vt, Maine, Mass,Conn., NY, Hawaii",
    "authorized": true,
    "name": "Bro. Paul Crawford",
    "email": "paulcrawnh@comcast.net",
    "phone": 6035821717,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": false,
    "take_actions": "Join the Earth Bill Network, Coordinate on Congressional Outreach, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "7/19/2023 15:33:49",
    "support": true,
    "org_name": "Progressives for Climate",
    "url": "",
    "states": "Colorado",
    "authorized": true,
    "name": "Annie Baker",
    "email": "Pforclimate@gmail.com",
    "phone": "(843) 732-6037",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "7/23/2023 15:27:06",
    "support": true,
    "org_name": "Brushwood Center at Ryerson Woods",
    "url": "brushwoodcenter.org",
    "states": "Illinois",
    "authorized": true,
    "name": "Catherine Game",
    "email": "cgame@brushwoodcenter.org",
    "phone": 2246332425,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "7/24/2023 21:52:27",
    "support": true,
    "org_name": "It’s Easy Being Green",
    "url": "Itseasybeinggreen.org",
    "states": "New York State",
    "authorized": true,
    "name": "Sharon Waskow",
    "email": "Itseasybeinggreen.uws@gmail.com",
    "phone": 9175833238,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "7/31/2023 13:43:18",
    "support": true,
    "org_name": "Franciscan Action Network",
    "url": "Franciscanaction.org",
    "states": "Nation Policy",
    "authorized": true,
    "name": "Bro. Paul Crawford",
    "email": "paulcrawnh@comcast.net",
    "phone": 6035821717,
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": false,
    "take_actions": "Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "9/20/2023 7:37:54",
    "support": true,
    "org_name": "Laudato Si Movement",
    "url": "https://laudatosimovement.org/",
    "states": "USA, over 110 countries",
    "authorized": true,
    "name": "Anna Johnson",
    "email": "anna.j@laudatosimovement.org",
    "phone": 9719988844,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "9/24/2023 12:13:19",
    "support": true,
    "org_name": "Peace Boat US",
    "url": "www.peaceboat-us.org",
    "states": "New York, USA",
    "authorized": true,
    "name": "Emilie McGlone",
    "email": "emilie@peaceboat-us.org",
    "phone": 2126877214,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network",

  },
  {
    "timestamp": "10/4/2023 10:27:44",
    "support": true,
    "org_name": "The Shalom Center",
    "url": "FB: https://www.facebook.com/TheShalomCenter IG: @the_shalom_center/",
    "states": "USA",
    "authorized": true,
    "name": "Nate DeGroot",
    "email": "ndegroot@theshalomcenter.org",
    "phone": 9783356672,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "10/13/2023 15:07:30",
    "support": true,
    "org_name": "Warheads to Windmills Coalition",
    "url": "www.warheadstowindmills.org",
    "states": "MA, PA, CA, ME, NY,",
    "authorized": true,
    "name": "Timmon Wallis",
    "email": "timmon@nuclearban.us",
    "phone": "631-507-8686",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "11/1/2023 13:58:19",
    "support": true,
    "org_name": "Earthjustice",
    "url": "www.earthjustice.org",
    "states": "National",
    "authorized": true,
    "name": "Chris Espinosa",
    "email": "CEspinosa@earthjustice.org",
    "phone": "202-793-2313",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "11/6/2023 16:44:05",
    "support": true,
    "org_name": "Interfaith Power & Light",
    "url": "https://interfaithpowerandlight.org/",
    "states": "National",
    "authorized": true,
    "name": "Tiffany Hartung",
    "email": "tiffany@interfaithpowerandlight.org",
    "phone": "248-933-2451",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "",

  },
  {
    "timestamp": "11/7/2023 11:36:19",
    "support": true,
    "org_name": "Ohalah:the Association of Rabbis and Cantors for Jewish Renewal",
    "url": "Ohalah.org",
    "states": "Many states of the United States, Europe, Latin America",
    "authorized": true,
    "name": "Rain Zohav",
    "email": "rainzohav@gmail.com",
    "phone": 2406202923,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "11/7/2023 11:57:37",
    "support": true,
    "org_name": "Coalition on the Environment and Jewish Life",
    "url": "coejl.org ; @coejl (Instagram and Twitter)",
    "states": "U.S. (National)",
    "authorized": true,
    "name": "Israel Harris",
    "email": "israel@coejl.org",
    "phone": 2025453651,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "11/7/2023 13:02:31",
    "support": true,
    "org_name": "Jewish Earth Alliance PA",
    "url": "",
    "states": "PA",
    "authorized": true,
    "name": "Phyllis Blumberg",
    "email": "Phyllis2723@gmail.com",
    "phone": 6103241786,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Join the Earth Bill Network",

  },
  {
    "timestamp": "11/7/2023 19:21:01",
    "support": true,
    "org_name": "Jewish Earth Alliance So. California",
    "url": "",
    "states": "CA",
    "authorized": true,
    "name": "Carol Singer",
    "email": "normcarol@cox.net",
    "phone": "949-275-3552",
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "11/8/2023 19:59:34",
    "support": true,
    "org_name": "Revitalize Community Development Corporation",
    "url": "www.RevitalizeCDC.com, Facebook.com/RevitalizeCDC, Instagram @RevitalizeCDC, Linkedin @RevitalizeCDC",
    "states": "Massachusetts, U.S.",
    "authorized": true,
    "name": "Colleen Shanley-Loveless",
    "email": "cloveless@revitalizecdc.com",
    "phone": "Cell: 860-669-9701 or Office: 413-788-0014",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts",

  },
  {
    "timestamp": "11/10/2023 14:53:40",
    "support": true,
    "org_name": "Extinction Rebellion Peace",
    "url": "https://xrpeace.org/",
    "states": "United States, United Kingdom",
    "authorized": true,
    "name": "Cynthia Papermaster",
    "email": "cynthia_papermaster@yahoo.com",
    "phone": "510-365-1500",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "11/11/2023 18:13:04",
    "support": true,
    "org_name": "Jim Owles Liberal Democratic Club",
    "url": "jimowles.org",
    "states": "New York",
    "authorized": true,
    "name": "Allen Roskoff",
    "email": "aroskoff@mac.com",
    "phone": "917-553-7180",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "11/16/2023 19:00:23",
    "support": true,
    "org_name": "Jewish Earth Alliance Bay Area",
    "url": "",
    "states": "Bay Area, CA",
    "authorized": true,
    "name": "Louise Lipsey",
    "email": "climatelouise@icloud.com",
    "phone": "",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Join the Earth Bill Network",

  },
  {
    "timestamp": "11/16/2023 20:34:39",
    "support": true,
    "org_name": "NOoSPHERE Arts",
    "url": "www.noosphere-arts.nyc",
    "states": "New York",
    "authorized": true,
    "name": "Sol Kjok",
    "email": "director@noosphere-arts.nyc",
    "phone": "718 389-8228",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "11/21/2023 16:13:03",
    "support": true,
    "org_name": "Santa Fe Forest Coalition",
    "url": "www.santafeforestcoalition.org",
    "states": "New Mexico",
    "authorized": true,
    "name": "Sam Hitt",
    "email": "sam@wildwatershed.org",
    "phone": 5054381057,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts",

  },
  {
    "timestamp": "11/22/2023 22:17:18",
    "support": true,
    "org_name": "Unite North Metro Denver",
    "url": "none",
    "states": "Colorado",
    "authorized": true,
    "name": "Fran FrainAguirre",
    "email": "jaguirrejja@aol.com",
    "phone": 3034775928,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "11/28/2023 16:27:32",
    "support": true,
    "org_name": "Change the Chamber & Lobby for Climate",
    "url": "changethechamber.org",
    "states": "United States - nationwide with a focus on Michigan, Wisconsin, Pennsylvania, Nevada, Georgia, and Arizona",
    "authorized": true,
    "name": "Evey Mengelkoch",
    "email": "evangeline.mengelkoch@gmail.com",
    "phone": "(541) 731-8662",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts",

  },
  {
    "timestamp": "1/23/2024 19:39:28",
    "support": true,
    "org_name": "350 Mass",
    "url": "https://350mass.betterfutureproject.org/",
    "states": "Massachusetts",
    "authorized": true,
    "name": "Carolyn C. Barthel",
    "email": "carolyncbarthel@gmail.com",
    "phone": 5083350848,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join shared Marketing Efforts",

  },
  {
    "timestamp": "2/5/2024 12:05:44",
    "support": true,
    "org_name": "1000 Grandmothers for Future Generations",
    "url": "https://www.1000grandmothers.com/",
    "states": "California",
    "authorized": true,
    "name": "Susan Penner",
    "email": "susanpennerbybay@gmail.com",
    "phone": 5104073532,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "2/5/2024 14:06:20",
    "support": true,
    "org_name": "Ocean Conservation Research",
    "url": "www.OCR.org",
    "states": "International",
    "authorized": true,
    "name": "Michael Stocker",
    "email": "mstocker@OCR.org",
    "phone": 4154647220,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network",

  },
  {
    "timestamp": "2/22/2024 9:44:00",
    "support": true,
    "org_name": "The Community Church of New York Unitarian Universalist",
    "url": "www.ccny.org",
    "states": "New York, NY",
    "authorized": true,
    "name": "Starling Carter",
    "email": "scarter@ccny.org",
    "phone": "(908)427-0398",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Join shared Marketing Efforts",

  },
  {
    "timestamp": "3/11/2024 12:26:29",
    "support": true,
    "org_name": "350 Salem Oregon",
    "url": "https://www.350salemor.org/",
    "states": "Oregon",
    "authorized": true,
    "name": "Philip H Carver",
    "email": "philiphcarver@gmail.com",
    "phone": "503-562-9878",
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "3/13/2024 16:24:01",
    "support": true,
    "org_name": "GreenFaith",
    "url": "",
    "states": "International",
    "authorized": true,
    "name": "Fletcher Harper",
    "email": "fletcher@greenfaith.org",
    "phone": 2013900094,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "",

  },
  {
    "timestamp": "4/5/2024 20:36:50",
    "support": true,
    "org_name": "350 Bay Area Action",
    "url": "https://350bayareaaction.org",
    "states": "California",
    "authorized": true,
    "name": "Nora Privitera",
    "email": "noraprivitera@comcast.net",
    "phone": 5104845992,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "4/27/2024 9:37:35",
    "support": true,
    "org_name": "The Enviro Show",
    "url": "http://envirosho.blogspot.com",
    "states": "Northeast U.S.",
    "authorized": true,
    "name": "Don Ogden",
    "email": "enviroshow@valleyfreeradio.org",
    "phone": "413-584-1160",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "5/8/2024 15:18:16",
    "support": true,
    "org_name": "Pax Christi New York State",
    "url": "www.paxchristinys.org",
    "states": "NY",
    "authorized": true,
    "name": "Rosemarie Pace",
    "email": "nypaxchristi@gmail.com",
    "phone": "718-255-1215",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "5/8/2024 20:53:39",
    "support": true,
    "org_name": "UU Catskills Climate Action Team",
    "url": "https://www.uucatskills.org/climate-action-team",
    "states": "New York",
    "authorized": true,
    "name": "Kathryn Kassner",
    "email": "kathrynkassner@gmail.com",
    "phone": 8457562715,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Join the Earth Bill Network, Coordinate on Congressional Outreach",

  },
  {
    "timestamp": "5/21/2024 22:17:13",
    "support": true,
    "org_name": "Rivers & Mountains GreenFaith",
    "url": "https://www.rivers-mountains-greenfaith.org",
    "states": "New York (Upper Hudson Valley)",
    "authorized": true,
    "name": "Michael Richardson",
    "email": "rivers.mountains@icloud.com",
    "phone": "845-489-5959",
    "logo": "",
    "alt_email": "",
    "organize": true,
    "use_logo": true,
    "take_actions": "Email our Lists",

  },
  {
    "timestamp": "5/23/2024 9:59:48",
    "support": true,
    "org_name": "Faith in Place Action Fund",
    "url": "www.faithinplaceaction.org",
    "states": "IL, IN, WI",
    "authorized": true,
    "name": "Rev. Brian Sauder",
    "email": "brian@faithinplace.org",
    "phone": 2176491898,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  },
  {
    "timestamp": "5/30/2024 9:48:02",
    "support": true,
    "org_name": "AMERICAN PUBLIC HEALTH ASSOCIATION",
    "url": "APHA.ORG",
    "states": "CÔTE-D'IVOIRE",
    "authorized": true,
    "name": "DAOUDA ADEGBOYE",
    "email": "dave.flint@yahoo.fr",
    "phone": "+2250749870201",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts",

  },
  {
    "timestamp": "5/30/2024 9:51:54",
    "support": true,
    "org_name": "ECOAMERICA",
    "url": "https://ecoamerica.mobilize.io/",
    "states": "CÔTE-D'IVOIRE",
    "authorized": true,
    "name": "DAOUDA ADEGBOYE",
    "email": "dave.flint@yahoo.fr",
    "phone": "+2250749870201",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts",

  },
  {
    "timestamp": "6/24/2024 11:32:35",
    "support": true,
    "org_name": "Church Women United in New York State",
    "url": "www.cwu.org",
    "states": "New York State",
    "authorized": true,
    "name": "Mary Smith",
    "email": "smithmarym@yahoo.com",
    "phone": "111-111-1111",
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": false,
    "take_actions": "",

  },
  {
    "timestamp": "6/24/2024 11:51:59",
    "support": true,
    "org_name": "Regenerative Agriculture Coalition",
    "url": "https://www.youtube.com/@FarmVoicesProject",
    "states": "United States",
    "authorized": true,
    "name": "Donald Viecelli",
    "email": "viecelli@comcast.net",
    "phone": 8474774425,
    "logo": "",
    "alt_email": "",
    "organize": false,
    "use_logo": true,
    "take_actions": "Email our Lists, Join the Earth Bill Network, Coordinate on Congressional Outreach, Join shared Marketing Efforts, Organize volunteers or staff by Congressional District",

  }
]